### ISSUE TITLE
Potential issue with template file

### ISSUE THREAD

**Issue by kastnerp** [roninsharma25/Graduation-Requirements-Validator#1]
Hi Ronin,

When I run your deployment with your `freshmanExample.csv` example I currently get: 

`````
KeyError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
`````

Best,

Patrick

**Comment by roninsharma25** [comment]
Hi Patrick,

I have tested the file in the repository on multiple browsers and haven't been able to replicate your error. Can you try downloading the file again or changing browsers? Does the error also occur for the other file (seniorExample.csv)?

Best,
Ronin

**Comment by kastnerp** [comment]
The `freshmanExample.csv` works now, not sure what went wrong last time. Thank you!

However, downloading the template directly from the app still throws the key error because the file is formatted differently from what is shipping in the repo, see screenshot.

![image](https://user-images.githubusercontent.com/1919773/169628176-d3bf4196-e55f-4798-ab74-86c7174f96d4.png)

Best,

Patrick

**Comment by roninsharma25** [comment]
Thanks for the catch! I just updated it but let me know if the problem still persists.

**Comment by kastnerp** [comment]
Works, thank you.
